#!/usr/bin/env python
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, K: int, A: "List[int]", B: "List[int]"):
    diff_sum=0
    for a, b in zip(A,B):
        diff_sum+=abs(a-b)

    if diff_sum>K:
        print(NO)
    else:
        if (diff_sum+K)%2==0:
            print(YES)
        else:
            print(NO)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, A, B)

if __name__ == '__main__':
    main()
