#!/usr/bin/env python3
import sys

def change_base(value:int,base:int):
    if value//base:
        return change_base(value//base,base)+str(value % base)
    return str(value % base)


def solve(N: int, K: int):
    base_8_str=str(N)
    for i in range(K):
        deci=int(base_8_str,8)
        base_9=change_base(deci,9)
        base_8_str=base_9.replace("8","5")
    print(base_8_str)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, K)

if __name__ == '__main__':
    main()
