#!/usr/bin/env python3
import sys


def solve(H: int, W: int):
    if H==1 or W==1:
        return H*W
    else:
        return ((H+1)//2)*((W+1)//2)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    print(solve(H, W))
    

if __name__ == '__main__':
    main()
